### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by cmgriffing** [xrochoa/angular-principles#2]
Should there be a section for testing?

If so it should probably mention both Testcafe and Protractor with links for each.

For protractor, I ended up making a bunch of utility methods, should we extract those to a library and link to it from here? No worries if not, just a thought.

eg: (there are a few more, but this is just to give you an idea of what they do.)
```javascript
  clickElement(selector) {
    browser.waitForAngular();
    browser.wait(function() {
      return element(by.css(selector)).isPresent();
    }, 5000);
    this.scrollToElement(selector);
    element(by.css(selector)).click();
  }

  enterText(options = {
    selector: '',
    text: ''
  }) {
    browser.waitForAngular();
    browser.wait(function() {
      return element(by.css(options.selector)).isPresent();
    }, 5000);
    this.scrollToElement(options.selector);
    element(by.css(options.selector)).clear();
    element(by.css(options.selector)).sendKeys(options.text);
  }
```

**Comment by xrochoa** [comment]
Hey Chris. I'm back at the office. Yeah, the idea of the library sounds cool. I'll probably be busy to work on it due to my new project but feel free to send me a link if you already have something up. I'll update this section in the next days.
